## Problem Statement
Given below is a dataframe df
```
import pandas as pd
df = pd.DataFrame([[0.23,'f1'],[5.36,'f2']],
                  index = list('pq'),
                  columns = list('ab'))
              
```

To Perform :

> Change the column name from ' a' to ' A'.

> Add a new column ' c' filled with random values.

> Change the datatype of column ' A' values to complex.

> Display rows whose any of the element matches with any element of the given list:

```
lst = ['f30','f50','f2','f0'] 
```

In [1]:
# given dataframe

import pandas as pd

df = pd.DataFrame(
    [[0.23, 'f1'], [5.36, 'f2']],
    index=list('pq'),
    columns=list('ab')
)
print(df)

      a   b
p  0.23  f1
q  5.36  f2

In [4]:

# changing column name from a to A
df.rename(columns = {'a':'A'}, inplace = True) 
df

      A   b
p  0.23  f1
q  5.36  f2

In [6]:
# adding a new column c filled with random values
import numpy as np
df['C'] = np.random.rand(2)

In [7]:
df

      A   b         C
p  0.23  f1  0.819669
q  5.36  f2  0.155617

In [8]:
# changing the values of column A to complex type
df['A'] = df['A'].astype(complex)

In [9]:
df

            A   b         C
p  0.23+0.00j  f1  0.819669
q  5.36+0.00j  f2  0.155617

In [10]:
# Displaying rows whose any of the element matches with any element of the given list
lst = ['f30','f50','f2','f0']

print(df[df.isin(lst).any(axis=1)])

            A   b         C
q  5.36+0.00j  f2  0.155617